// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD05YrLl8ll974Yvh_m9VjLiiYyhpf6FBw',
    appId: '1:277447074008:web:da2e5b56682e43161077ad',
    messagingSenderId: '277447074008',
    projectId: 'p-chats-26652',
    authDomain: 'p-chats-26652.firebaseapp.com',
    storageBucket: 'p-chats-26652.firebasestorage.app',
    measurementId: 'G-YHMM16RSHZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1R7H_TmVB5Cy24PrwlpX2OV-spH6rMC8',
    appId: '1:277447074008:android:3c2d1a1352171fab1077ad',
    messagingSenderId: '277447074008',
    projectId: 'p-chats-26652',
    storageBucket: 'p-chats-26652.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCi0gUuoFNX__vkRbo4MwEt0eMAp9hrX4g',
    appId: '1:277447074008:ios:59f6d9a0649b6a701077ad',
    messagingSenderId: '277447074008',
    projectId: 'p-chats-26652',
    storageBucket: 'p-chats-26652.firebasestorage.app',
    iosBundleId: 'com.example.chats',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCi0gUuoFNX__vkRbo4MwEt0eMAp9hrX4g',
    appId: '1:277447074008:ios:59f6d9a0649b6a701077ad',
    messagingSenderId: '277447074008',
    projectId: 'p-chats-26652',
    storageBucket: 'p-chats-26652.firebasestorage.app',
    iosBundleId: 'com.example.chats',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD05YrLl8ll974Yvh_m9VjLiiYyhpf6FBw',
    appId: '1:277447074008:web:6d4843b542ddb90f1077ad',
    messagingSenderId: '277447074008',
    projectId: 'p-chats-26652',
    authDomain: 'p-chats-26652.firebaseapp.com',
    storageBucket: 'p-chats-26652.firebasestorage.app',
    measurementId: 'G-QLCH690Z0F',
  );
}
